### PR TITLE
no angry messages

### PR DESCRIPTION
**Pull request by ihatespawn**
merge asap

### CODE REVIEW

**Comment by goodtube4u** [comment]
No.

**Comment by ihatespawn** [comment]
why

**Comment by SpiritAxolotl** [comment]
why

**Comment by ihatespawn** [comment]
just host your own instance and don't tell others to send angry messages to the creators of cobalt
if you don't want to pay, just use this: https://github.com/render-yaml/cobalt

<sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub>a</sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup>

**Comment by KwiatekMiki** [comment]
> No.

why

**Comment by kwiatlol** [comment]
why

**Comment by 0wef** [comment]
why

**Comment by k190-web** [comment]
why

**Comment by 7egh** [comment]
why

**Comment by goodtube4u** [comment]
Hm, let me think. You released a free, for public use API - which I chose to use - in order to let people download stuff.
I want everyone to be able to download music, etc just like you.

Yesturday you made a change that redirected all of our users to your website.

Your website then showed the following message:
"The website you were on is abusing our free api for their own profit. We blocked them from accessing our servers. This is why you're here. If you're tired of ads, shady redirects, and also care about your privacy and sanity, switch to the bright side: cobalt.tools"

Which is...kinda crazy? Especially as this is not for profit and not redirecting anyone. Ironically you've redirected these users to your homepage, with a large donate button at the bottom.

I try to make peace with you, saying "Hey can we credit you? Put a link to your site in our interface?"

And I get a really crazy accusational message in return...saying I'm lying and all this insane stuff. Oh man. Can I address some of what was said?
1. The reason we're obscuring your server is because it should be hidden in this sort of grey area product. Same goes for the video servers.
2. This is a headless frontend, yes it's using one type of video server but others are soon to follow. That's the idea, this can fetch data from anything that is connected directly on Youtube.
3. The less users know about how this works the better you dopes.
4. I'm prompting users to send you angry messages. Yes I am, which is something that if you weren't blind, you'd realise is in JEST and FUNNY. Jesus christ you guys are high strung.

Anyway. I've had just about enough of this madness. I really think we should be working together, but this is....oh man, of all the servers I chose to connect for downloads. It's incredible, really.

**Comment by ihatespawn** [comment]
> You released a free, for public use API

wukko*

> The reason we're obscuring your server is because it should be hidden in this sort of grey area product.
wukko* and i wouldn't obscure it and would credit it in multiple places immediately after implementing it, including github and code

> Yesturday you made a change that redirected all of our users to your website.

Yesterday* wukko*

> Your website then showed the following message:
"The website you were on is abusing our free api for their own profit. We blocked them from accessing our servers. This is why you're here. If you're tired of ads, shady redirects, and also care about your privacy and sanity, switch to the bright side: cobalt.tools"

wukko isn't making a block website for everything he blocks so he reused an old block website
<sup>+ wukko*</sup>

> I try to make peace with you, saying "Hey can we credit you? Put a link to your site in our interface?"

with wukko* and you should've done that before the block, there 

> I'm prompting users to send you angry messages. Yes I am

AND YOU SHOULDN'T. JUST HOST YOUR OWN INSTANCE, IT'S NOT THAT HARD
JUST DO THESE STEPS: https://github.com/render-yaml/cobalt/blob/main/README.md
YOU DON'T EVEN NEED TO PAY FOR THAT

> Anyway. I've had just about enough of this madness. I really think we should be working together, but this is....oh man, of all the servers I chose to connect for downloads. It's incredible, really.

don't tell this to me

---

also, please read this again: https://github.com/imputnet/cobalt/issues/600#issuecomment-2198479609

**Comment by SpiritAxolotl** [comment]
OWN THAT FRAUD

**Comment by iHATEgoodtubeanditscreatorforalot** [comment]
please stop changing issue names to say positive thongs please, it actually makes this worse and very sus. and also contact me as i said already

**Pull request closed without merging**
